WIP: Integrate Searx metasearch engine into FreedomBox
freedombox/FreedomBox pull request #1199
Opened 2018-01-13 11:08 UTC by JosephKiranBabu

The Debian package of Searx is not in a working condition yet. There's a patch that must be merged.
This PR is functionally complete but I'm not totally confident about it since I haven't seen it working with the current Searx Debian package.

Please do not risk merging this in release 0.21.0

2018-01-15 06:35 UTC, SunilMohanAdapa requested changes
Here are some preliminary comments.

2018-01-15 06:35 UTC, SunilMohanAdapa commented on actions/searx
> +    action_utils.webserver_enable('searx-plinth')
Should be consider enabling/disabling uwsgi application configuration?

2018-01-15 06:35 UTC, SunilMohanAdapa commented on plinth/utils.py
> +        f.write(contents)
Please use `file_handle` (or so) instead of `f` for consistent naming of variables.

2018-01-15 06:35 UTC, SunilMohanAdapa commented on actions/searx
> +        secret_key = os.urandom(16).hex()
Searx is using this as a key for doing HMAC-SHA256. A minimum key size of 32 bytes is recommended. 64 bytes is probably better.

Using the `secrets` module might be a better than using os.urandom() directly.

2020-08-06 16:29 UTC, jvalleroy commented
Repository moved to https://salsa.debian.org/freedombox-team/freedombox.

2020-08-06 16:29 UTC, closed without merging